/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const ElBadge: typeof import('element-plus/es')['ElBadge']
  const ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElCalendar: typeof import('element-plus/es')['ElCalendar']
  const ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
  const ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
  const ElTransfer: typeof import('element-plus/es')['ElTransfer']
}
